
apiVersion: v1
kind: ReplicaSet
metadata:
  name: https
  labels:
    app: https
spec:
  minReadySeconds: 1
  replicas: 2
  selector:
    LabelSelector: 
      matchLabels:
        app: httpd
      template:
        metadata:
          name:
          labels:
            app: httpd
      spec:
        containers:
          - name: httpd
            image: httpd 
            ports:
              - ContainerPort: 80
            readinessProbe: 1
            failureThreshold: 3
            periodSeconds: 20

